### ISSUE TITLE
several issues

### ISSUE THREAD

**Issue by Manuelibt** [sarmbruster/thinkpad_x1_yoga_rotation#3]
Hi, 

I installed the script on my new debian 9 installation and got several issues. 
The touchpad is stil active
No touch recognition after using the pen
sometimes the monitor scalation changes after rotating.

here is tho terminal output: 

`./thinkpad_x1_yoga_rotation.py
2017-07-05 19:50:40,424 - root - INFO - detected wacom devices: ['Wacom Co.,Ltd. Pen and multitouch sensor Pen stylus', 'Wacom Co.,Ltd. Pen and multitouch sensor Pen eraser', 'Wacom Co.,Ltd. Pen and multitouch sensor Finger touch']
2017-07-05 19:50:40,426 - root - INFO - found stylus Wacom Co.,Ltd. Pen and multitouch sensor Pen stylus
2017-07-05 19:50:40,426 - root - INFO - found finger touch Wacom Co.,Ltd. Pen and multitouch sensor Finger touch
2017-07-05 19:50:40,426 - root - INFO - found touchpad and trackpoints ['TPPS/2 IBM TrackPoint', 'SynPS/2 Synaptics TouchPad']
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "./thinkpad_x1_yoga_rotation.py", line 50, in monitor_acpi_events
    socketACPI.connect("/var/run/acpid.socket")
FileNotFoundError: [Errno 2] No such file or directory
`

**Comment by sarmbruster** [comment]
Have not used Debian 9 so far - being on Ubuntu 17.04 currently.
Can you please check if  `acpid` and `acpi-support` are installed? If not, install them.

**Comment by Manuelibt** [comment]
Hi 
thanks for your quick answere.
Now both programms are installed, but the touchpad for example is still active..

**Comment by MiriUll** [comment]
Hey,
I had this problem on Fedora as well.
Print Out the found devices and then change the name of disabled device to the right name of the Touchpad ;)

**Comment by Manuelibt** [comment]
wow that was fast, too. 
Sorry, forgot to say, you are facing a very interested noob..

Changed the .py at this line
from 
` else:
                for x in touch_and_track:
                    cmd_and_log(["xinput", "disable", x])`

to
` else:
                for x in touch_and_track:
                    cmd_and_log(["xinput", "disable", "SynPS/2 Synaptics TouchPad"])`

But the touchpad is still active.

**Comment by MiriUll** [comment]
Have a look at the line where you define touch_and_track. I had to change "TouchPad" into "Touchpad" and it worked.
Your output says "INFO - found touchpad and trackpoints" so maybe try "touchpad"

**Comment by Manuelibt** [comment]
Tried to change it in several ways, but no result.. 
It is not just the touchpad thats still working, also the trackpoint is still active... 

Is there a way to enable the monitorkeyboard on the login screen?
Thanks for your effort.

**Comment by sarmbruster** [comment]
`touch_and_track` is set up in https://github.com/sarmbruster/thinkpad_x1_yoga_rotation/blob/master/thinkpad_x1_yoga_rotation.py#L125. It parses output of `xinput --list --name-only` and filters for lines containing `TrackPoint` and `TouchPad`.

What's your output of `xinput --list --name-only`?
Can you amend a fresh console log output?

A monitor keyboard should be started automatically when flipped over, just install package `onboard`. in case you use a different one you need to change the code in line 74.

**Comment by Manuelibt** [comment]
here is my console output: 
`xinput --list --name-only`
```
Virtual core pointer
Virtual core XTEST pointer
Wacom Co.,Ltd. Pen and multitouch sensor Pen stylus
SynPS/2 Synaptics TouchPad
TPPS/2 IBM TrackPoint
Wacom Co.,Ltd. Pen and multitouch sensor Pen eraser
Wacom Co.,Ltd. Pen and multitouch sensor Finger touch
Virtual core keyboard
Virtual core XTEST keyboard
Power Button
Video Bus
Sleep Button
Integrated Camera
AT Translated Set 2 keyboard
ThinkPad Extra Buttons
```

Onboard is already installed

**Comment by sarmbruster** [comment]
Looks rather similar to output of my X1 

```
Virtual core pointer
Virtual core XTEST pointer
SynPS/2 Synaptics TouchPad
TPPS/2 IBM TrackPoint
Wacom Co.,Ltd. Pen and multitouch sensor Finger touch
Wacom Co.,Ltd. Pen and multitouch sensor Pen stylus
Wacom Co.,Ltd. Pen and multitouch sensor Pen eraser
Logitech K750
Logitech M570
Virtual core keyboard
Virtual core XTEST keyboard
Power Button
Video Bus
Sleep Button
AT Translated Set 2 keyboard
ThinkPad Extra Buttons
Integrated Camera
Logitech K750
C-Media Electronics Inc. ThinkPad OneLink Plus Dock Audio

```
(being attached to OneLink dock currently - so there are some more devices)

Can you add a fresh log output from the script when you start it up and also when you flip it over?

**Comment by Manuelibt** [comment]
Hi, 
here is the output. Is it the right behavior, that nothing happens when I am just flipping the screen over, without rotation? As soon as i rotated the screen, i got an output. 

`./thinkpad_x1_yoga_rotation.py `

```
2017-07-06 14:19:39,358 - root - INFO - detected wacom devices: ['Wacom Co.,Ltd. Pen and multitouch sensor Pen stylus', 'Wacom Co.,Ltd. Pen and multitouch sensor Pen eraser', 'Wacom Co.,Ltd. Pen and multitouch sensor Finger touch']
2017-07-06 14:19:39,359 - root - INFO - found stylus Wacom Co.,Ltd. Pen and multitouch sensor Pen stylus
2017-07-06 14:19:39,360 - root - INFO - found finger touch Wacom Co.,Ltd. Pen and multitouch sensor Finger touch
2017-07-06 14:19:39,360 - root - INFO - found touchpad and trackpoints ['TPPS/2 IBM TrackPoint']
2017-07-06 14:19:39,361 - root - INFO - connected to acpi socket <module 'socket' from '/usr/lib/python3.5/socket.py'>
2017-07-06 14:19:49,178 - root - INFO - dbus signal indicates orientation change to bottom-up
2017-07-06 14:19:49,370 - root - INFO - running ['xsetwacom', '--set', 'Wacom Co.,Ltd. Pen and multitouch sensor Pen stylus', 'rotate', 'half'] with exit code 0
2017-07-06 14:19:49,378 - root - INFO - running ['xsetwacom', '--set', 'Wacom Co.,Ltd. Pen and multitouch sensor Pen eraser', 'rotate', 'half'] with exit code 0
2017-07-06 14:19:49,386 - root - INFO - running ['xsetwacom', '--set', 'Wacom Co.,Ltd. Pen and multitouch sensor Finger touch', 'rotate', 'half'] with exit code 0
2017-07-06 14:19:52,683 - root - INFO - dbus signal indicates orientation change to right-up
2017-07-06 14:19:54,090 - root - INFO - running ['xsetwacom', '--set', 'Wacom Co.,Ltd. Pen and multitouch sensor Pen stylus', 'rotate', 'cw'] with exit code 0
2017-07-06 14:19:54,093 - root - INFO - running ['xsetwacom', '--set', 'Wacom Co.,Ltd. Pen and multitouch sensor Pen eraser', 'rotate', 'cw'] with exit code 0
2017-07-06 14:19:54,098 - root - INFO - running ['xsetwacom', '--set', 'Wacom Co.,Ltd. Pen and multitouch sensor Finger touch', 'rotate', 'cw'] with exit code 0
2017-07-06 14:19:54,098 - root - INFO - dbus signal indicates orientation change to normal
2017-07-06 14:19:55,548 - root - INFO - running ['xsetwacom', '--set', 'Wacom Co.,Ltd. Pen and multitouch sensor Pen stylus', 'rotate', 'none'] with exit code 0
2017-07-06 14:19:55,556 - root - INFO - running ['xsetwacom', '--set', 'Wacom Co.,Ltd. Pen and multitouch sensor Pen eraser', 'rotate', 'none'] with exit code 0
2017-07-06 14:19:55,560 - root - INFO - running ['xsetwacom', '--set', 'Wacom Co.,Ltd. Pen and multitouch sensor Finger touch', 'rotate', 'none'] with exit code 0
2017-07-06 14:19:56,889 - root - INFO - dbus signal indicates orientation change to left-up
2017-07-06 14:19:58,358 - root - INFO - running ['xsetwacom', '--set', 'Wacom Co.,Ltd. Pen and multitouch sensor Pen stylus', 'rotate', 'ccw'] with exit code 0
2017-07-06 14:19:58,374 - root - INFO - running ['xsetwacom', '--set', 'Wacom Co.,Ltd. Pen and multitouch sensor Pen eraser', 'rotate', 'ccw'] with exit code 0
2017-07-06 14:19:58,381 - root - INFO - running ['xsetwacom', '--set', 'Wacom Co.,Ltd. Pen and multitouch sensor Finger touch', 'rotate', 'ccw'] with exit code 0
2017-07-06 14:20:00,394 - root - INFO - dbus signal indicates orientation change to normal
2017-07-06 14:20:01,795 - root - INFO - running ['xsetwacom', '--set', 'Wacom Co.,Ltd. Pen and multitouch sensor Pen stylus', 'rotate', 'none'] with exit code 0
2017-07-06 14:20:01,811 - root - INFO - running ['xsetwacom', '--set', 'Wacom Co.,Ltd. Pen and multitouch sensor Pen eraser', 'rotate', 'none'] with exit code 0
2017-07-06 14:20:01,821 - root - INFO - running ['xsetwacom', '--set', 'Wacom Co.,Ltd. Pen and multitouch sensor Finger touch', 'rotate', 'none'] with exit code 0
```

**Comment by sarmbruster** [comment]
This looks like you're not receiving acpi events when your tablet is completely flipped over. Use `sudo acpi_listen` to check for events. I get this:
```
ibm/hotkey LEN0068:00 00000080 000060f0
ibm/hotkey LEN0068:00 00000080 000060f0
video/tabletmode TBLT 0000008A 00000001
 PNP0C14:03 000000b0 00000000
video/tabletmode TBLT 0000008A 00000000
 PNP0C14:03 000000b0 00000000
```
The first to events are triggered while moving the lid, the other to when lid is completely flipped over and moving back from that position.

**Comment by Manuelibt** [comment]
hi, 
this is what i get: 
```
ibm/hotkey LEN0268:00 00000080 000060c0
ibm/hotkey LEN0268:00 00000080 000060f0
ibm/hotkey LEN0268:00 00000080 000060c0
ibm/hotkey LEN0268:00 00000080 000060f0
ibm/hotkey LEN0268:00 00000080 000060c0
 PNP0C14:04 000000b0 00000000
ibm/hotkey LEN0268:00 00000080 000060c0
 PNP0C14:04 000000b0 00000000
ibm/hotkey LEN0268:00 00000080 000060c0
ibm/hotkey LEN0268:00 00000080 000060f0
ibm/hotkey LEN0268:00 00000080 000060c0
ibm/hotkey LEN0268:00 00000080 000060f0
```

**Comment by sarmbruster** [comment]
change l.59 to reflect your different setup:
```
eventACPIDisplayPositionChange = b" PNP0C14:04 000000b0 00000000\n"
```
If that helps I need to understand why we're seeing different numbers and change the script to handle all cases.

**Comment by Manuelibt** [comment]
Changed this line, but the touchpad is still enabled. 

I'm wondering about this output you got: video/tabletmode TBLT 0000008A 00000000
It seems like my laptop is not recognizing this mode. 

Here is what i get when i run the changed sript, from beginning till end of prog. 

`./thinkpad_x1_yoga_rotation.py 
2017-07-06 22:18:34,408 - root - INFO - detected wacom devices: ['Wacom Co.,Ltd. Pen and multitouch sensor Finger touch', 'Wacom Co.,Ltd. Pen and multitouch sensor Pen stylus', 'Wacom Co.,Ltd. Pen and multitouch sensor Pen eraser']

2017-07-06 22:18:34,410 - root - INFO - found stylus Wacom Co.,Ltd. Pen and multitouch sensor Pen stylus

2017-07-06 22:18:34,410 - root - INFO - found finger touch Wacom Co.,Ltd. Pen and multitouch sensor Finger touch

2017-07-06 22:18:34,410 - root - INFO - found touchpad and trackpoints ['TPPS/2 IBM TrackPoint']
2017-07-06 22:18:34,412 - root - INFO - connected to acpi socket <module 'socket' from '/usr/lib/python3.5/socket.py'>
^CProcess Process-1:
Process Process-2:
Traceback (most recent call last):
  File "./thinkpad_x1_yoga_rotation.py", line 155, in <module>
    main(options)
  File "./thinkpad_x1_yoga_rotation.py", line 148, in main
    loop.run()
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 577, in run
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "./thinkpad_x1_yoga_rotation.py", line 56, in monitor_acpi_events
    event = socketACPI.recv(4096)
  File "./thinkpad_x1_yoga_rotation.py", line 85, in monitor_stylus_proximity
    for line in out.stdout:
KeyboardInterrupt
KeyboardInterrupt
    raise KeyboardInterrupt
KeyboardInterrupt
2017-07-06 22:19:16,875 - root - INFO - running ['xinput', 'enable', 'TPPS/2 IBM TrackPoint'] with exit code 0
2017-07-06 22:19:16,877 - root - INFO - running ['xsetwacom', '--set', 'Wacom Co.,Ltd. Pen and multitouch sensor Finger touch', 'rotate', 'none'] with exit code 0
2017-07-06 22:19:16,879 - root - INFO - running ['xsetwacom', '--set', 'Wacom Co.,Ltd. Pen and multitouch sensor Pen stylus', 'rotate', 'none'] with exit code 0
2017-07-06 22:19:16,881 - root - INFO - running ['xsetwacom', '--set', 'Wacom Co.,Ltd. Pen and multitouch sensor Pen eraser', 'rotate', 'none'] with exit code 0 `

**Comment by Manuelibt** [comment]
Problem solved for me... 
Moved from Debian to Kubuntu. In Kubuntu i get the tabletmode output. 
But i had to change the line 59 like you mentioned.

**Comment by Manuelibt** [comment]
Hey, 

now you'll have some fun with me ;). 

Because it is a new machine i just installed kubuntu instead of debian. Tried to run the script - 
Before I had to install docotp and before this pip - than installed acpi. 

Listened to acpi - Tabletmode is recognized and PNP0C14:04. Changed line 59 like you mentioned. 

Tada flip is working, touchpad disabled, onboard pops up (after installing it) BUT no screen rotation. 

Any clue ?

Here is my output of the script: 
`thinkpad_x1_yoga_rotation.py 
2017-07-06 23:45:20,667 - root - INFO - detected wacom devices: ['Wacom Co.,Ltd. Pen and multitouch sensor Finger touch', 'Wacom Co.,Ltd. Pen and multitouch sensor Pen stylus', 'Wacom Co.,Ltd. Pen and multitouch sensor Pen eraser']
2017-07-06 23:45:20,668 - root - INFO - found stylus Wacom Co.,Ltd. Pen and multitouch sensor Pen stylus
2017-07-06 23:45:20,669 - root - INFO - found finger touch Wacom Co.,Ltd. Pen and multitouch sensor Finger touch
2017-07-06 23:45:20,669 - root - INFO - found touchpad and trackpoints ['TPPS/2 IBM TrackPoint', 'SynPS/2 Synaptics TouchPad']
2017-07-06 23:45:20,670 - root - INFO - connected to acpi socket <module 'socket' from '/usr/lib/python3.5/socket.py'>
2017-07-06 23:45:27,564 - root - INFO - display position change detected, laptop mode False
2017-07-06 23:45:27,631 - root - INFO - running ['xinput', 'disable', 'TPPS/2 IBM TrackPoint'] with exit code 0
2017-07-06 23:45:27,673 - root - INFO - running ['xinput', 'disable', 'SynPS/2 Synaptics TouchPad'] with exit code 0
nohup: ignoriere Eingabe und leite Standardfehlerausgabe auf Standardausgabe um
2017-07-06 23:45:27,679 - root - INFO - started onboard with pid 2467
2017-07-06 23:45:37,865 - root - INFO - display position change detected, laptop mode True
2017-07-06 23:45:37,872 - root - INFO - running ['xinput', 'enable', 'TPPS/2 IBM TrackPoint'] with exit code 0
2017-07-06 23:45:37,877 - root - INFO - running ['xinput', 'enable', 'SynPS/2 Synaptics TouchPad'] with exit code 0
2017-07-06 23:45:37,877 - root - INFO - onboard pid 2467
2017-07-06 23:45:37,877 - root - INFO - stopping onboard
`

**Comment by sarmbruster** [comment]
Try a fresh kernel (either 4.11.x or 4.12.x) from http://kernel.ubuntu.com/~kernel-ppa/mainline. Don't fully remember details, but support for the accelerometer was fixed in 4.9.x. Unfortunately it didn't work in 4.10.x but is fixed again since 4.11.x.

**Comment by Manuelibt** [comment]
Yeah!Now it is working.
thankyou so much for that script and for your help. 

There is just one issue left, that i have no keyboard on the login screen. 
Is it working for you? 

And something off topic, how do you handle the screenresolution? 
I rescaled and set the fonts on 120 dpi but in some progs like blender or cinerella the gui is so tiny.. Is there a way to rescale the progs individually?

**Comment by sarmbruster** [comment]
I only get onboard when already logged in.
There are some applications out there that don't support dpi scaling - unfortunately I don't have to use any of those :-) 
Since your issue is resolved I'll close that ticket now. If you experience more issues, feel free to open another one.
